#ifndef THONO_CONFIG_H
#define THONO_CONFIG_H

#define THONO_SPEED 8.0
#define THONO_LENS_SIZE 0.1
#define THONO_ZOOM_FACTOR 1.1
#define THONO_LENS_FACTOR 1.2

#define THONO_SELECTION_COLOR 0.7, 0.7, 0.7, 1.0
#define THONO_FLASHLIGHT_COLOR 0.0, 0.0, 0.0, 0.8
#define THONO_BACKGROUND_COLOR (0x20 / 255.0), (0x20 / 255.0), (0x20 / 255.0), 1.0

#define THONO_WALLPAPER_RESTORE_PATH_DEFAULT ".local/share/wallpaper"

#define THONO_SELECTION_PENDING_FRAMES_SKIP 5

#endif // THONO_CONFIG_H
