#ifndef THONO_CONFIG_H
#define THONO_CONFIG_H

#define THONO_SPEED 8.0
#define THONO_LENS_SIZE 0.1
#define THONO_ZOOM_FACTOR 1.1
#define THONO_LENS_FACTOR 1.2

#define THONO_FLASHLIGHT_COLOR 0.2, 0.2, 0.2, 1.0
#define THONO_BACKGROUND_COLOR 0.1, 0.1, 0.1, 1.0

#endif // THONO_CONFIG_H
